### ISSUE TITLE
[ID] Halaman FAQ outdated

### ISSUE THREAD

**Issue by vzrenggamani** [osu-Indonesia-Contributors/osu-wiki#6]
Iseng" buka discord eh, ada yang bahas FAQ iseng" intip file nya dan bandingin sama yang english ehh `oudated`

#

- BRANCH : [outdated-faq](https://github.com/osu-Indonesia-Contributors/osu-wiki/tree/outdated-faq)
- File : [id.md](https://github.com/osu-Indonesia-Contributors/osu-wiki/blob/outdated-faq/wiki/FAQ/id.md)
- File EN (terjemah awal): [en.md](https://github.com/osu-Indonesia-Contributors/osu-wiki/blob/outdated-faq/wiki/FAQ/en.md) `kalo bisa ambil dari master saja`

#

Kayaknya lebih enak ngerewrite daripada lanjutin TL, kebanyakan yang aneh TL nya ;/

Refer to issues : #2 
BCC : @osu-Indonesia-Contributors/alih-bahasa 
BCC : @osu-Indonesia-Contributors/merger

**Comment by fajar13k** [comment]
Total is around 730 Lines worth of Markdown Code.
I'll pick from Line 77 - 306.

NB: I'll update this comment if i decide to go further
